### PR TITLE
Established dir structure, added assignment files, fixed issue 1

### PR DESCRIPTION
**Pull request by hansenwu**
Moved assignment 1 files to a1 dir, added assignment PDF and SQL dump, wrote index HTML to comply with requirements and solve issue 1.

### CODE REVIEW

**Comment by alohakealii** [comment]
I don't think we need to put the html and php files in a subdirectory. From what he said we are going to keep building on the same stuff, so we're going to be reusing them anyways.

Also, looking at the assignment again, it looks to me like we're supposed to use the radio buttons and checkboxes to change the query to the database.

**Comment by hansenwu** [comment]
Can we add columns to the DB? Currently I think there's only three columns, which somewhat limits the possible actions. It's fine as it is, just weird to, for example, enter your username to change your name, and vice versa.

**Comment by alohakealii** [comment]
Yeah, we need to add more. Gender and/or major or something. We all need to talk and figure out what web app we're making.

For this assignment we aren't doing anything with the form except querying the database.

**Comment by hansenwu** [comment]
What does the assignment mean by different queries to the database? I was envisioning the either first or last name queries would fulfill the requirement.

**Comment by quibs** [comment]
I originally wanted to do something that we could reuse for our project but
its difficult to do that while conforming to a1 requirements.

I'll probably do the entire assignment and upload it on drive so I don't
conflict with whatever you guys are doing right now. It wouldn't take me
very long. I'll let you guys choose whether you want to use it or not.

David, do you think it might be better to add us on git so that we can make
changes without making pull requests?

**Comment by hansenwu** [comment]
We need to find a time to go over the project then, and make sure we know what we're building so we can all work on it.

**Comment by quibs** [comment]
Yeah, I been telling you guys to think up project ideas! Maybe meet monday
night on hangouts to discuss ideas?

**Comment by alohakealii** [comment]
If everyone works directly on the master branch then there's not much of a point in using git, we might as well just use google drive. You should have the ability to do it now, but I'm against the idea.

As simple as this assignment is, I don't think we should worry about it being a part of our project at all. We can add a few things to the database and make these two files work for the assignment, and it won't be difficult to change later. I've never really seen this assignment as being part of the overall project, but more of an introductory assignment for everyone to learn how xampp and all its pieces work.

**Comment by quibs** [comment]
I think it'll be fine (at least for school project purposes). I've done 2
projects with everyone working on the master branch with no problems.
Generally, we work on different parts of the project. Git still has the
advantage of syncing files and tracking changes over google docs. I'm sure
you can do it on google docs if you wanted to, but it wouldn't be as easy.

Since we're all working on the same 2-3 files right now for a single
assignment, I see your point. As we spread out and work on different
files/parts of the project, I think it'll be okay. That said, I am not
familiar with managing branches, so I'd be interested in learning. Either
option is fine.

I've put an updated version of assignment 1 on the google drive. I think
I've touched on most/all requirements, but I haven't double checked yet.
Feel free to edit them as you see fit. The users table will be removed and
replaced by the profiles table if we submit that version as he only wants a
single table.

**Comment by alohakealii** [comment]
I've had a lot of ridiculous problems with people overwriting things other people did, breaking and changing things just not realizing what they're doing, and frequent merging conflicts when people work on the same area of code. But you're right, those were only when we were working on the same files. If/when we all work on different files it would be fine.

**Comment by hansenwu** [comment]
With Git, we could make small changes to other code on the fly though, without the assigned person needing to be available.

**Pull request closed without merging**
